<script src="<?= THEME_ASSET_URL ?>assets/js/jquery.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/jquery-ui.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/jquery.fitvids.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/bootstrap.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/magnific.popup.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/imagesloaded.pkgd.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/isotope.pkgd.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/owl.carousel.min.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/booking.form.js"></script>
<script src="<?= THEME_ASSET_URL ?>assets/js/contact.form.js"></script>